# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 400)
        Dialog.setMinimumSize(QtCore.QSize(600, 400))
        Dialog.setMaximumSize(QtCore.QSize(600, 400))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.d_copy = QtWidgets.QPushButton(self.widget)
        self.d_copy.setObjectName("d_copy")
        self.horizontalLayout.addWidget(self.d_copy)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.d_ok = QtWidgets.QPushButton(self.widget)
        self.d_ok.setObjectName("d_ok")
        self.horizontalLayout.addWidget(self.d_ok)
        self.d_cancel = QtWidgets.QPushButton(self.widget)
        self.d_cancel.setObjectName("d_cancel")
        self.horizontalLayout.addWidget(self.d_cancel)
        self.gridLayout.addWidget(self.widget, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.p_tab = QtWidgets.QWidget()
        self.p_tab.setObjectName("p_tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.p_tab)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.p_tab)
        self.widget_2.setMinimumSize(QtCore.QSize(200, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.p_table = QtWidgets.QTableWidget(self.widget_2)
        self.p_table.setObjectName("p_table")
        self.p_table.setColumnCount(2)
        self.p_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.p_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.p_table.setHorizontalHeaderItem(1, item)
        self.verticalLayout_3.addWidget(self.p_table)
        self.p_chbox = QtWidgets.QCheckBox(self.widget_2)
        self.p_chbox.setObjectName("p_chbox")
        self.verticalLayout_3.addWidget(self.p_chbox)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.p_chart_widget = QtWidgets.QWidget(self.p_tab)
        self.p_chart_widget.setObjectName("p_chart_widget")
        self.horizontalLayout_2.addWidget(self.p_chart_widget)
        self.tabWidget.addTab(self.p_tab, "")
        self.f_tab = QtWidgets.QWidget()
        self.f_tab.setObjectName("f_tab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.f_tab)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_4 = QtWidgets.QWidget(self.f_tab)
        self.widget_4.setMinimumSize(QtCore.QSize(200, 0))
        self.widget_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.f_table = QtWidgets.QTableWidget(self.widget_4)
        self.f_table.setObjectName("f_table")
        self.f_table.setColumnCount(2)
        self.f_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.f_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.f_table.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.f_table)
        self.f_chbox = QtWidgets.QCheckBox(self.widget_4)
        self.f_chbox.setObjectName("f_chbox")
        self.verticalLayout_2.addWidget(self.f_chbox)
        self.horizontalLayout_4.addWidget(self.widget_4)
        self.f_chart_widget = QtWidgets.QWidget(self.f_tab)
        self.f_chart_widget.setObjectName("f_chart_widget")
        self.horizontalLayout_4.addWidget(self.f_chart_widget)
        self.tabWidget.addTab(self.f_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.d_copy.setText(_translate("Dialog", "Copy to Frequency"))
        self.d_ok.setText(_translate("Dialog", "Ok"))
        self.d_cancel.setText(_translate("Dialog", "Cancel"))
        item = self.p_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Power"))
        item = self.p_table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Speed"))
        self.p_chbox.setText(_translate("Dialog", "Show in Abs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.p_tab), _translate("Dialog", "Power"))
        item = self.f_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Frequency"))
        item = self.f_table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Speed"))
        self.f_chbox.setText(_translate("Dialog", "Show in Abs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.f_tab), _translate("Dialog", "Frequency"))

